#dataset: "NYU" # "kitti", "kitti_360"
dataset: "kitti_360"

n_relations: 4

enable_log: false
kitti_root: '/path/to/semantic_kitti'
kitti_preprocess_root: '/path/to/kitti/preprocess/folder'
kitti_logdir: '/path/to/semantic_kitti/logdir'

NYU_root: '/monoscene/MonoScene/nyu/NYU_dataset/depthbin/'
NYU_preprocess_root: '/monoscene/MonoScene/nyu/NYU_dataset/depthbin/preprocess'
logdir: '/monoscene/logdir'

output_path: '/path/to/output'


fp_loss: true 
frustum_size: 8 
batch_size: 1
n_gpus: 0
num_workers_per_gpu: 0 
exp_prefix: "exp"
run: 1
lr: 1e-4
weight_decay: 1e-4 

context_prior: true

relation_loss: true 
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true

project_1_2: true
project_1_4: true
project_1_8: true




